application: webrtctestexp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: webrtc.application
  secure: always

- url: /desktop
  script: webrtc.application

- url: /message
  script: webrtc.application
  secure: always

- url: /mobile
  script: webrtc.application

- url: /js
  static_dir: js

- url: /components
  static_dir: components 

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /data
  static_dir: data 

- url: /favicon.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico

- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt

libraries: 
- name: jinja2
  version: latest



